### ISSUE TITLE
A small code-writing mistake in Chinese translation version.

### ISSUE THREAD

**Issue by wddpct** [dotnet/docs.zh-cn#39] opened 2017-07-19 03:56 UTC
link to [query-a-collection-of-objects](https://docs.microsoft.com/zh-cn/dotnet/csharp/linq/query-a-collection-of-objects)

in the `QueryHighScores` method, there is a small mistake. 
```
Console.WriteLine($"item.Name:-15}{item.Score}}")
```

Should be corrected for

```
Console.WriteLine($"{item.Name:-15}{item.Score}")
```

**Comment by lextm** [comment] 2017-07-19 13:54
You can send a pull request.

**Comment by John0King** [comment] 2017-09-18 01:57
@wddpct   what does `item.Name:-15 ` mean ?

**Comment by nokura** [comment] 2017-09-23 00:35
@mairaw will you look at the suggested change? Thank you!

**Comment by mairaw** [comment] 2017-09-23 01:10
I've opened a PR @nokura. @John0King, that was a mistake. It should be `itemName,15`.

**Comment by John0King** [comment] 2017-09-23 01:58
@mairaw  cool, I never notice string-interpolation can do things like this !  :+1:

**Comment by mairaw** [comment] 2017-09-23 05:48
I've noticed today that our topic doesn't cover that scenario as well. I think it'd be nice to add.

**Comment by mairaw** [comment] 2017-09-25 19:20
Reopening since the version that I fixed was the English one. Chinese version should be fixed after translation happens.

**Comment by mairaw** [comment] 2017-09-30 00:49
Thank you for reporting this issue @wddpct. I've rebuilt the Chinese content and not the issue is fixed here too. @nokura you should run full builds from time to time for all loc repos to make sure your build captures dependencies fixes like code snippets.

**Closed by mairaw** 2017-09-30 00:49 UTC
